name: Deploy To GithubPage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.0
      - name: Get yarn cache dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use yarn Cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install

      - name: Download comments from wordpress
        run: curl -u "github-action:%{WP_TOKEN}" ${WP_COMMENTS_API_URL} -o source/_data/comments.json
        env:
          WP_TOKEN: ${{ secrets.WP_TOKEN }}
          WP_COMMENTS_API_URL: ${{ secrets.WP_COMMENTS_API_URL }}
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGE_TOKEN }}
          publish_dir: ./public
